//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoukeyNetget.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class globalPara {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal globalPara() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoukeyNetget.Resources.globalPara", typeof(globalPara).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MS Sqlserver 的本地化字符串。
        /// </summary>
        internal static string DatabaseType2 {
            get {
                return ResourceManager.GetString("DatabaseType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MySql 的本地化字符串。
        /// </summary>
        internal static string DatabaseType3 {
            get {
                return ResourceManager.GetString("DatabaseType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重名则进行覆盖 的本地化字符串。
        /// </summary>
        internal static string DownloadFileDealType1 {
            get {
                return ResourceManager.GetString("DownloadFileDealType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重名则按照序号进行排序保存 的本地化字符串。
        /// </summary>
        internal static string DownloadFileDealType2 {
            get {
                return ResourceManager.GetString("DownloadFileDealType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重名则按照网站路径进行保存 的本地化字符串。
        /// </summary>
        internal static string DownloadFileDealType3 {
            get {
                return ResourceManager.GetString("DownloadFileDealType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不做输出控制 的本地化字符串。
        /// </summary>
        internal static string ExportLimit1 {
            get {
                return ResourceManager.GetString("ExportLimit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据指定条件删除整行 的本地化字符串。
        /// </summary>
        internal static string ExportLimit10 {
            get {
                return ResourceManager.GetString("ExportLimit10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须包含指定条件 的本地化字符串。
        /// </summary>
        internal static string ExportLimit11 {
            get {
                return ResourceManager.GetString("ExportLimit11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将符合条件的数据置为空 的本地化字符串。
        /// </summary>
        internal static string ExportLimit12 {
            get {
                return ResourceManager.GetString("ExportLimit12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将Unicode码转换成汉字 的本地化字符串。
        /// </summary>
        internal static string ExportLimit13 {
            get {
                return ResourceManager.GetString("ExportLimit13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需进行HTML解码 的本地化字符串。
        /// </summary>
        internal static string ExportLimit14 {
            get {
                return ResourceManager.GetString("ExportLimit14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去除网页代码，但保留段落换行符号 的本地化字符串。
        /// </summary>
        internal static string ExportLimit15 {
            get {
                return ResourceManager.GetString("ExportLimit15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去除网页代码，但将段落换行符号替换成\r\n 的本地化字符串。
        /// </summary>
        internal static string ExportLimit16 {
            get {
                return ResourceManager.GetString("ExportLimit16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动编号，起始值 的本地化字符串。
        /// </summary>
        internal static string ExportLimit17 {
            get {
                return ResourceManager.GetString("ExportLimit17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将指定符号替换成分行符号，并进行拆分行处理 的本地化字符串。
        /// </summary>
        internal static string ExportLimit18 {
            get {
                return ResourceManager.GetString("ExportLimit18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用正则从采集数据中二次提取数据 的本地化字符串。
        /// </summary>
        internal static string ExportLimit19 {
            get {
                return ResourceManager.GetString("ExportLimit19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出时去掉网页符号 的本地化字符串。
        /// </summary>
        internal static string ExportLimit2 {
            get {
                return ResourceManager.GetString("ExportLimit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式化字符串 的本地化字符串。
        /// </summary>
        internal static string ExportLimit20 {
            get {
                return ResourceManager.GetString("ExportLimit20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动输出下载文件地址 的本地化字符串。
        /// </summary>
        internal static string ExportLimit21 {
            get {
                return ResourceManager.GetString("ExportLimit21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从采集网址中获取数据 的本地化字符串。
        /// </summary>
        internal static string ExportLimit22 {
            get {
                return ResourceManager.GetString("ExportLimit22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从采集数据中获取 的本地化字符串。
        /// </summary>
        internal static string ExportLimit23 {
            get {
                return ResourceManager.GetString("ExportLimit23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集数据组合 的本地化字符串。
        /// </summary>
        internal static string ExportLimit24 {
            get {
                return ResourceManager.GetString("ExportLimit24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串解码 的本地化字符串。
        /// </summary>
        internal static string ExportLimit25 {
            get {
                return ResourceManager.GetString("ExportLimit25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入一个固定值 的本地化字符串。
        /// </summary>
        internal static string ExportLimit26 {
            get {
                return ResourceManager.GetString("ExportLimit26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出时附加前缀 的本地化字符串。
        /// </summary>
        internal static string ExportLimit3 {
            get {
                return ResourceManager.GetString("ExportLimit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出时附加后缀 的本地化字符串。
        /// </summary>
        internal static string ExportLimit4 {
            get {
                return ResourceManager.GetString("ExportLimit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左起去掉字符 的本地化字符串。
        /// </summary>
        internal static string ExportLimit5 {
            get {
                return ResourceManager.GetString("ExportLimit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右起去掉字符 的本地化字符串。
        /// </summary>
        internal static string ExportLimit6 {
            get {
                return ResourceManager.GetString("ExportLimit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换其中符合条件的字符 的本地化字符串。
        /// </summary>
        internal static string ExportLimit7 {
            get {
                return ResourceManager.GetString("ExportLimit7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去掉字符串首尾空格 的本地化字符串。
        /// </summary>
        internal static string ExportLimit8 {
            get {
                return ResourceManager.GetString("ExportLimit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出时采用正则表达式进行替换 的本地化字符串。
        /// </summary>
        internal static string ExportLimit9 {
            get {
                return ResourceManager.GetString("ExportLimit9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string GDataType1 {
            get {
                return ResourceManager.GetString("GDataType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash 的本地化字符串。
        /// </summary>
        internal static string GDataType2 {
            get {
                return ResourceManager.GetString("GDataType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        internal static string GDataType3 {
            get {
                return ResourceManager.GetString("GDataType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        internal static string GDataType4 {
            get {
                return ResourceManager.GetString("GDataType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能提取页面标题 的本地化字符串。
        /// </summary>
        internal static string GDataType5 {
            get {
                return ResourceManager.GetString("GDataType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能提取文章正文 的本地化字符串。
        /// </summary>
        internal static string GDataType6 {
            get {
                return ResourceManager.GetString("GDataType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能提取发布时间 的本地化字符串。
        /// </summary>
        internal static string GDataType7 {
            get {
                return ResourceManager.GetString("GDataType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从头递增 的本地化字符串。
        /// </summary>
        internal static string IncrByCondition1 {
            get {
                return ResourceManager.GetString("IncrByCondition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从尾递增 的本地化字符串。
        /// </summary>
        internal static string IncrByCondition2 {
            get {
                return ResourceManager.GetString("IncrByCondition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不做任意格式的限制 的本地化字符串。
        /// </summary>
        internal static string LimitSign1 {
            get {
                return ResourceManager.GetString("LimitSign1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动采集正文 的本地化字符串。
        /// </summary>
        internal static string LimitSign10 {
            get {
                return ResourceManager.GetString("LimitSign10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动采集发布时间 的本地化字符串。
        /// </summary>
        internal static string LimitSign11 {
            get {
                return ResourceManager.GetString("LimitSign11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动采集来源 的本地化字符串。
        /// </summary>
        internal static string LimitSign12 {
            get {
                return ResourceManager.GetString("LimitSign12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配非网页符号字符 的本地化字符串。
        /// </summary>
        internal static string LimitSign2 {
            get {
                return ResourceManager.GetString("LimitSign2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只匹配中文 的本地化字符串。
        /// </summary>
        internal static string LimitSign3 {
            get {
                return ResourceManager.GetString("LimitSign3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只匹配双字节字符 的本地化字符串。
        /// </summary>
        internal static string LimitSign4 {
            get {
                return ResourceManager.GetString("LimitSign4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只匹配数字 的本地化字符串。
        /// </summary>
        internal static string LimitSign5 {
            get {
                return ResourceManager.GetString("LimitSign5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只匹配字母数字及常用字符 的本地化字符串。
        /// </summary>
        internal static string LimitSign6 {
            get {
                return ResourceManager.GetString("LimitSign6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义匹配字符 的本地化字符串。
        /// </summary>
        internal static string LimitSign7 {
            get {
                return ResourceManager.GetString("LimitSign7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义正则匹配表达式 的本地化字符串。
        /// </summary>
        internal static string LimitSign8 {
            get {
                return ResourceManager.GetString("LimitSign8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动采集标题 的本地化字符串。
        /// </summary>
        internal static string LimitSign9 {
            get {
                return ResourceManager.GetString("LimitSign9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永不失效 的本地化字符串。
        /// </summary>
        internal static string MonitorInvalidType1 {
            get {
                return ResourceManager.GetString("MonitorInvalidType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按照日期失效 的本地化字符串。
        /// </summary>
        internal static string MonitorInvalidType2 {
            get {
                return ResourceManager.GetString("MonitorInvalidType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到符合的网址失效 的本地化字符串。
        /// </summary>
        internal static string MonitorInvalidType3 {
            get {
                return ResourceManager.GetString("MonitorInvalidType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过指定运行次数计划失效 的本地化字符串。
        /// </summary>
        internal static string PlanDisabledType1 {
            get {
                return ResourceManager.GetString("PlanDisabledType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过指定时间计划失效 的本地化字符串。
        /// </summary>
        internal static string PlanDisabledType2 {
            get {
                return ResourceManager.GetString("PlanDisabledType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效 的本地化字符串。
        /// </summary>
        internal static string PlanState1 {
            get {
                return ResourceManager.GetString("PlanState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失效 的本地化字符串。
        /// </summary>
        internal static string PlanState2 {
            get {
                return ResourceManager.GetString("PlanState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期 的本地化字符串。
        /// </summary>
        internal static string PlanState3 {
            get {
                return ResourceManager.GetString("PlanState3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取Cookie类 的本地化字符串。
        /// </summary>
        internal static string PluginType1 {
            get {
                return ResourceManager.GetString("PluginType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据处理类 的本地化字符串。
        /// </summary>
        internal static string PluginType2 {
            get {
                return ResourceManager.GetString("PluginType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据发布类 的本地化字符串。
        /// </summary>
        internal static string PluginType3 {
            get {
                return ResourceManager.GetString("PluginType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不发布数据 的本地化字符串。
        /// </summary>
        internal static string PublishType1 {
            get {
                return ResourceManager.GetString("PublishType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布到Access数据库 的本地化字符串。
        /// </summary>
        internal static string PublishType2 {
            get {
                return ResourceManager.GetString("PublishType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布到MS Sql Server 的本地化字符串。
        /// </summary>
        internal static string PublishType3 {
            get {
                return ResourceManager.GetString("PublishType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布到Excel文件 的本地化字符串。
        /// </summary>
        internal static string PublishType4 {
            get {
                return ResourceManager.GetString("PublishType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布到文本文件 的本地化字符串。
        /// </summary>
        internal static string PublishType5 {
            get {
                return ResourceManager.GetString("PublishType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布到MySql数据库 的本地化字符串。
        /// </summary>
        internal static string PublishType6 {
            get {
                return ResourceManager.GetString("PublishType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线发布 的本地化字符串。
        /// </summary>
        internal static string PublishType7 {
            get {
                return ResourceManager.GetString("PublishType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络矿工任务 的本地化字符串。
        /// </summary>
        internal static string RunTaskType1 {
            get {
                return ResourceManager.GetString("RunTaskType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库任务 的本地化字符串。
        /// </summary>
        internal static string RunTaskType2 {
            get {
                return ResourceManager.GetString("RunTaskType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它任务 的本地化字符串。
        /// </summary>
        internal static string RunTaskType3 {
            get {
                return ResourceManager.GetString("RunTaskType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅采集数据 的本地化字符串。
        /// </summary>
        internal static string TaskRunType1 {
            get {
                return ResourceManager.GetString("TaskRunType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集并发布数据 的本地化字符串。
        /// </summary>
        internal static string TaskRunType2 {
            get {
                return ResourceManager.GetString("TaskRunType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接入库，支持大数据量 的本地化字符串。
        /// </summary>
        internal static string TaskRunType3 {
            get {
                return ResourceManager.GetString("TaskRunType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据网址采集网页数据 的本地化字符串。
        /// </summary>
        internal static string TaskType1 {
            get {
                return ResourceManager.GetString("TaskType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集整站网页数据 的本地化字符串。
        /// </summary>
        internal static string TaskType2 {
            get {
                return ResourceManager.GetString("TaskType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集RSS聚合数据 的本地化字符串。
        /// </summary>
        internal static string TaskType3 {
            get {
                return ResourceManager.GetString("TaskType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集ajax网页数据 的本地化字符串。
        /// </summary>
        internal static string TaskType4 {
            get {
                return ResourceManager.GetString("TaskType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增量采集 的本地化字符串。
        /// </summary>
        internal static string TaskType5 {
            get {
                return ResourceManager.GetString("TaskType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部参数任务 的本地化字符串。
        /// </summary>
        internal static string TaskType6 {
            get {
                return ResourceManager.GetString("TaskType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 靠左靠上 的本地化字符串。
        /// </summary>
        internal static string WatermarkPos1 {
            get {
                return ResourceManager.GetString("WatermarkPos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 靠左上下居中 的本地化字符串。
        /// </summary>
        internal static string WatermarkPos2 {
            get {
                return ResourceManager.GetString("WatermarkPos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 靠左靠下 的本地化字符串。
        /// </summary>
        internal static string WatermarkPos3 {
            get {
                return ResourceManager.GetString("WatermarkPos3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中靠上 的本地化字符串。
        /// </summary>
        internal static string WatermarkPos4 {
            get {
                return ResourceManager.GetString("WatermarkPos4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左右居中上下居中 的本地化字符串。
        /// </summary>
        internal static string WatermarkPos5 {
            get {
                return ResourceManager.GetString("WatermarkPos5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中靠下 的本地化字符串。
        /// </summary>
        internal static string WatermarkPos6 {
            get {
                return ResourceManager.GetString("WatermarkPos6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 靠右靠上 的本地化字符串。
        /// </summary>
        internal static string WatermarkPos7 {
            get {
                return ResourceManager.GetString("WatermarkPos7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 靠右上下居中 的本地化字符串。
        /// </summary>
        internal static string WatermarkPos8 {
            get {
                return ResourceManager.GetString("WatermarkPos8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 靠右靠下 的本地化字符串。
        /// </summary>
        internal static string WatermarkPos9 {
            get {
                return ResourceManager.GetString("WatermarkPos9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不编码 的本地化字符串。
        /// </summary>
        internal static string WebCode1 {
            get {
                return ResourceManager.GetString("WebCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        internal static string WebCode2 {
            get {
                return ResourceManager.GetString("WebCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gb2312 的本地化字符串。
        /// </summary>
        internal static string WebCode3 {
            get {
                return ResourceManager.GetString("WebCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTF-8 的本地化字符串。
        /// </summary>
        internal static string WebCode4 {
            get {
                return ResourceManager.GetString("WebCode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gbk 的本地化字符串。
        /// </summary>
        internal static string WebCode5 {
            get {
                return ResourceManager.GetString("WebCode5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 big5 的本地化字符串。
        /// </summary>
        internal static string WebCode6 {
            get {
                return ResourceManager.GetString("WebCode6", resourceCulture);
            }
        }
    }
}
